-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "player1_score" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "player2_score" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ranked" BOOLEAN NOT NULL DEFAULT false;
